### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Lesruez93** [paynow/Paynow-NodeJS-SDK#14]
.

**Comment by melmups** [comment]
Hi @Lesruez93. What exactly is not working in 1.0.5? Could you please post a snip of the error that you're getting?

**Comment by melmups** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
 

Please use the template above to describe the problem you're running into

**Comment by melmups** [comment]
@Lesruez93. PR #15 fixes a lot of bugs and those fixes will be in version 1.0.6 which is set to go live sometime this evening. Hopefully that will have the fix for the issues you're running into
