### ISSUE TITLE
I keep getting "Hashes do not match!" Am I  doing something wrong?

### ISSUE THREAD

**Issue by IamTinashe** [paynow/Paynow-NodeJS-SDK#20]
I keep getting "Hashes do not match!" Am I  doing something wrong?

**Comment by iammerus** [comment]
Hi Tinashe. 

Please use this format to report a bug so we can help you figure out what's going on 😉


**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by user3470** [comment]
Still facing this issue
Check #26

**Comment by Teenayc** [comment]
facing same issue

**Comment by Teenayc** [comment]
An error occured while initiating transaction Error: Hashes do not match!
    at Paynow.parse 
Your application has broken an axle TypeError: Cannot read properties of undefined (reading 'success')

Any help
